import type { ICatalogueProduct } from './types'

const STORAGE =
  'Хранить в сухом, защищённом от прямых солнечных лучей месте при температуре от +5°C до +25°C. После вскрытия упаковки хранить в холодильнике и употребить в течение 3 суток.'

const SOSTAV =
  'Вода, сахар, растительные масла, сухое молоко, какао-порошок, эмульгаторы, ароматизаторы. Может содержать следы орехов и глютена.'

const SHORT_DESCRIPTION = `
  <p>Самолётом из Армении. Инжир [смоковница, фига, винная ягода] относится к семейству толстянковых. Плод обладает тонкой кожурой, представляет собой мелкую семянку, располагающуюся внутри мясистого цветоложа грушевидной формы, весит 20-75 г.</p>
`

const TAGS = [
  { key: 'no-sugar', title: 'Без сахара', background: '#f3d1c4' },
  { key: 'no-lactose', title: 'Без лактозы', background: '#d9d2da' },
  { key: 'halal', title: 'Халяль', background: '#d6eb9f' },
  { key: 'frozen', title: 'Заморозка', background: '#c8e6f3' },
]

const buildImages = (prefix: string, count: number) =>
  Array.from({ length: count }, (_, index) => ({
    id: `${prefix}-${index + 1}`,
    url: '/juice.png',
  }))

export const catalogueProducts: Record<string, ICatalogueProduct> = {
  '101': {
    id: '101',
    title: 'Хлебцы гречневые с морской солью',
    weight: '120 г',
    url: 'catalog/hlebcy-grechnevye',
    availableones: 8,
    imageUrl: '/juice.png',
    imageUrls: ['/juice.png', '/juice.png'],
    images: buildImages('101', 2),
    short_description: SHORT_DESCRIPTION,
    storage: STORAGE,
    sostav: SOSTAV,
    calories_amount: '285',
    bel_amount: '6,5',
    fats_amount: '12,3',
    ugl_amount: '34,8',
    related: ['102', '103'],
    variations: ['101'],
    tags: TAGS,
    price: '149 ₽',
  },
  '102': {
    id: '102',
    title: 'Миндальная паста без сахара',
    weight: '230 г',
    url: 'catalog/mindalnaya-pasta',
    availableones: 4,
    imageUrl: '/juice.png',
    imageUrls: ['/juice.png', '/juice.png', '/juice.png'],
    images: buildImages('102', 3),
    short_description: SHORT_DESCRIPTION,
    storage: STORAGE,
    sostav: SOSTAV,
    calories_amount: '290',
    bel_amount: '8,2',
    fats_amount: '15,1',
    ugl_amount: '20,6',
    related: ['101', '103'],
    variations: ['102'],
    tags: TAGS.slice(0, 3),
    price: '369 ₽',
  },
  '103': {
    id: '103',
    title: 'Кокосовые чипсы натуральные',
    weight: '90 г',
    url: 'catalog/kokosovye-chipsy',
    availableones: 3,
    imageUrl: '/juice.png',
    imageUrls: ['/juice.png'],
    images: buildImages('103', 1),
    short_description: SHORT_DESCRIPTION,
    storage: STORAGE,
    sostav: SOSTAV,
    calories_amount: '265',
    bel_amount: '4,1',
    fats_amount: '9,6',
    ugl_amount: '21,8',
    related: ['101', '102'],
    variations: ['103'],
    tags: TAGS.slice(1),
    price: '219 ₽',
  },
  '201': {
    id: '201',
    title: 'Натуральные свежие апельсины самолётом из Армении',
    weight: '500',
    ed_izm: 'г',
    url: 'catalog/apelsiny-armeniya',
    availableones: 12,
    imageUrl: '/juice.png',
    imageUrls: ['/juice.png', '/juice.png', '/juice.png'],
    images: buildImages('201', 3),
    short_description: SHORT_DESCRIPTION,
    storage: STORAGE,
    sostav: SOSTAV,
    calories_amount: '285',
    bel_amount: '6,5',
    fats_amount: '12,3',
    ugl_amount: '34,8',
    related: ['101', '102', '103'],
    variations: ['203', '201', '202'],
    tags: TAGS,
    price: '21 000 ₽',
  },
  '202': {
    id: '202',
    title: 'Натуральные свежие апельсины самолётом из Армении',
    weight: '1',
    ed_izm: 'кг',
    url: 'catalog/apelsiny-armeniya-1kg',
    availableones: 9,
    imageUrl: '/juice.png',
    imageUrls: ['/juice.png', '/juice.png'],
    images: buildImages('202', 2),
    short_description: SHORT_DESCRIPTION,
    storage: STORAGE,
    sostav: SOSTAV,
    calories_amount: '300',
    bel_amount: '7,1',
    fats_amount: '13,0',
    ugl_amount: '36,0',
    related: ['101', '102', '103'],
    variations: ['203', '201', '202'],
    tags: TAGS,
    price: '39 000 ₽',
  },
  '203': {
    id: '203',
    title: 'Натуральные свежие апельсины самолётом из Армении',
    weight: '250',
    ed_izm: 'г',
    url: 'catalog/apelsiny-armeniya-250',
    availableones: 6,
    imageUrl: '/juice.png',
    imageUrls: ['/juice.png', '/juice.png'],
    images: buildImages('203', 2),
    short_description: SHORT_DESCRIPTION,
    storage: STORAGE,
    sostav: SOSTAV,
    calories_amount: '240',
    bel_amount: '5,1',
    fats_amount: '10,0',
    ugl_amount: '30,2',
    related: ['101', '102', '103'],
    variations: ['203', '201', '202'],
    tags: TAGS,
    price: '11 900 ₽',
  },
}

export const initialProductId = '203'
